---
env:
  contexts:
    - name: target
      urls:
        - ${ZAP_TARGET}
      includePaths:
        - ${ZAP_TARGET}.*
jobs:
  - type: spider
    parameters:
      context: target
      maxDuration: 10
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: activeScan
    parameters:
      context: target
      maxScanDurationInMins: 20
  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: full.html
  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk
      reportFile: full.json
  - type: report
    parameters:
      template: sarif-json
      reportDir: /zap/wrk
      reportFile: full.sarif